# Generated by Django 4.2.3 on 2023-07-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsDetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
